name: "Install Docker"
description: "A GitHub Action to install Docker on the Linux (Ubuntu/Debian) runner environment."
author: "m-wrona"
branding:
  icon: "package"
  color: "yellow"

inputs:
  docker_version:
    description: "The version of Docker to install. Leave blank to install the latest version."
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Install Docker
      shell: bash
      run: |
        # Prepare 
        sudo apt-get update -y
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

        # Add Docker's official GPG key
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

        # Add Docker repository
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        # Install Docker
        sudo apt-get update -y
        if [[ "${{ inputs.docker_version }}" == "latest" ]]; then
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        else
          sudo apt-get install -y docker-ce=${{ inputs.docker_version }} docker-ce-cli=${{ inputs.docker_version }} containerd.io
        fi

        # Verify Docker installation
        docker --version
