name: "Check whether Docker Install Workflow works as expected."

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install_docker:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Docker
        uses: bigmikesolutions/install-docker-action@v1
      - name: Verify Docker installation
        run: docker --version